[2024-11-28T14:39:07.162+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T14:39:07.178+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_processing_dag.process_data_task manual__2024-11-28T14:39:04.560866+00:00 [queued]>
[2024-11-28T14:39:07.187+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_processing_dag.process_data_task manual__2024-11-28T14:39:04.560866+00:00 [queued]>
[2024-11-28T14:39:07.188+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-28T14:39:07.201+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_data_task> on 2024-11-28 14:39:04.560866+00:00
[2024-11-28T14:39:07.208+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=216) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-28T14:39:07.210+0000] {standard_task_runner.py:72} INFO - Started process 218 to run task
[2024-11-28T14:39:07.210+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_processing_dag', 'process_data_task', 'manual__2024-11-28T14:39:04.560866+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/data_processing_dag.py', '--cfg-path', '/tmp/tmp6eo4gji7']
[2024-11-28T14:39:07.212+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask process_data_task
[2024-11-28T14:39:07.256+0000] {task_command.py:467} INFO - Running <TaskInstance: data_processing_dag.process_data_task manual__2024-11-28T14:39:04.560866+00:00 [running]> on host 60ea90825a9a
[2024-11-28T14:39:07.587+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_processing_dag' AIRFLOW_CTX_TASK_ID='process_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T14:39:04.560866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T14:39:04.560866+00:00'
[2024-11-28T14:39:07.588+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T14:39:07.719+0000] {logging_mixin.py:190} INFO - Dane zosta≈Çy przetworzone i zapisane do /opt/***/dags/processed_stroke.csv
[2024-11-28T14:39:07.720+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-28T14:39:07.730+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T14:39:07.731+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_processing_dag, task_id=process_data_task, run_id=manual__2024-11-28T14:39:04.560866+00:00, execution_date=20241128T143904, start_date=20241128T143907, end_date=20241128T143907
[2024-11-28T14:39:07.788+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-28T14:39:07.806+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T14:39:07.811+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
