[2024-11-27T22:37:35.663+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:37:35.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:37:35.671+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:37:35.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:37:35.725+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:37:35.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:37:35.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:37:35.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.125 seconds
[2024-11-27T22:38:06.676+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:38:06.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:38:06.679+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:38:06.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:38:06.700+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:38:06.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:38:06.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:38:06.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.060 seconds
[2024-11-27T22:38:37.751+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:38:37.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:38:37.754+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:38:37.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:38:37.772+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:38:37.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:38:37.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:38:37.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.056 seconds
[2024-11-27T22:39:08.769+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:39:08.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:39:08.772+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:39:08.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:39:08.787+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:39:08.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:39:08.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:39:08.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.052 seconds
[2024-11-27T22:39:39.792+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:39:39.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:39:39.795+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:39:39.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:39:39.812+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:39:39.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:39:39.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:39:39.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.054 seconds
[2024-11-27T22:40:29.110+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:40:29.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:40:29.113+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:40:29.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:40:29.133+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:40:29.129+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:40:29.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:40:29.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T22:40:59.944+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:40:59.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:40:59.947+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:40:59.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:40:59.963+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:40:59.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:40:59.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:40:59.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T22:41:30.031+0000] {processor.py:186} INFO - Started process (PID=162) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:41:30.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:41:30.035+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:41:30.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:41:30.055+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:41:30.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:41:30.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:41:30.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.059 seconds
[2024-11-27T22:42:00.445+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:42:00.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:42:00.448+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:42:00.447+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:42:00.472+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:42:00.467+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:42:00.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:42:00.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.060 seconds
[2024-11-27T22:42:51.402+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:42:51.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:42:51.406+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:42:51.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:42:51.424+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:42:51.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:42:51.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:42:51.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.047 seconds
[2024-11-27T22:43:21.583+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:43:21.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:43:21.587+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:43:21.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:43:21.603+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:43:21.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:43:21.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:43:21.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
[2024-11-27T22:43:51.950+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:43:51.951+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:43:51.953+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:43:51.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:43:51.970+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:43:51.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:43:51.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:43:51.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
[2024-11-27T22:44:22.617+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:44:22.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:44:22.619+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:44:22.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:44:22.633+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:44:22.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:44:22.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:44:22.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.041 seconds
[2024-11-27T22:44:53.364+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:44:53.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:44:53.366+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:44:53.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:44:53.381+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:44:53.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:44:53.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:44:53.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.041 seconds
[2024-11-27T22:45:23.700+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:45:23.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:45:23.702+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:45:23.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:45:23.721+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:45:23.717+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:45:23.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:45:23.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.045 seconds
[2024-11-27T22:45:53.953+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:45:53.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:45:53.956+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:45:53.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:45:53.969+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:45:53.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:45:53.970+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:45:53.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.037 seconds
[2024-11-27T22:46:24.335+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:46:24.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:46:24.338+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:46:24.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:46:24.352+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:46:24.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:46:24.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:46:24.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T22:46:54.993+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:46:54.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:46:54.996+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:46:54.995+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:46:55.017+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:46:55.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:46:55.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:46:55.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T22:47:25.673+0000] {processor.py:186} INFO - Started process (PID=619) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:47:25.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:47:25.677+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:47:25.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:47:25.693+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:47:25.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:47:25.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:47:25.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.048 seconds
[2024-11-27T22:47:56.021+0000] {processor.py:186} INFO - Started process (PID=684) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:47:56.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:47:56.026+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:47:56.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:47:56.063+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:47:56.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:47:56.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:47:56.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.071 seconds
[2024-11-27T22:49:14.388+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:49:14.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:49:14.393+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:49:14.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:49:14.418+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:49:14.412+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:49:14.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:49:14.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.065 seconds
[2024-11-27T22:49:45.207+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:49:45.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:49:45.210+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:49:45.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:49:45.226+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:49:45.222+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:49:45.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:49:45.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.043 seconds
[2024-11-27T22:50:15.616+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:50:15.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:50:15.619+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:50:15.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:50:15.635+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:50:15.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:50:15.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:50:15.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.049 seconds
[2024-11-27T22:50:46.454+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:50:46.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:50:46.457+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:50:46.456+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:50:46.473+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:50:46.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:50:46.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:50:46.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.043 seconds
[2024-11-27T22:51:17.506+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:51:17.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:51:17.509+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:51:17.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:51:17.526+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:51:17.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:51:17.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:51:17.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
[2024-11-27T22:51:47.865+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:51:47.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:51:47.868+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:51:47.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:51:47.889+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:51:47.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:51:47.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:51:47.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.052 seconds
[2024-11-27T22:52:18.369+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:52:18.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:52:18.372+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:52:18.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:52:18.387+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:52:18.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:52:18.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:52:18.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.054 seconds
[2024-11-27T22:52:48.604+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:52:48.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:52:48.607+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:52:48.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:52:48.622+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:52:48.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:52:48.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:52:48.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.040 seconds
[2024-11-27T22:53:18.695+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:53:18.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:53:18.698+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:53:18.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:53:18.713+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:53:18.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:53:18.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:53:18.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T22:53:49.121+0000] {processor.py:186} INFO - Started process (PID=619) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:53:49.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:53:49.125+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:53:49.125+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:53:49.141+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:53:49.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:53:49.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:53:49.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
[2024-11-27T22:54:19.564+0000] {processor.py:186} INFO - Started process (PID=684) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:54:19.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:54:19.567+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:54:19.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:54:19.582+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:54:19.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:54:19.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:54:19.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T22:54:50.028+0000] {processor.py:186} INFO - Started process (PID=749) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:54:50.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:54:50.031+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:54:50.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:54:50.057+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:54:50.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:54:50.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:54:50.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.058 seconds
[2024-11-27T22:55:20.490+0000] {processor.py:186} INFO - Started process (PID=814) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:55:20.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:55:20.493+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:55:20.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:55:20.509+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:55:20.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:55:20.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:55:20.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.049 seconds
[2024-11-27T22:55:50.753+0000] {processor.py:186} INFO - Started process (PID=885) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:55:50.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:55:50.756+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:55:50.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:55:50.771+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:55:50.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:55:50.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:55:50.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T22:56:21.146+0000] {processor.py:186} INFO - Started process (PID=950) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:56:21.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:56:21.148+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:56:21.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:56:21.163+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:56:21.160+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:56:21.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:56:21.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.040 seconds
[2024-11-27T22:56:51.523+0000] {processor.py:186} INFO - Started process (PID=1015) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:56:51.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:56:51.526+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:56:51.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:56:51.544+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:56:51.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:56:51.545+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:56:51.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.057 seconds
[2024-11-27T22:57:21.768+0000] {processor.py:186} INFO - Started process (PID=1080) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:57:21.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:57:21.782+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:57:21.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:57:21.817+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:57:21.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:57:21.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:57:21.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.094 seconds
[2024-11-27T22:57:52.669+0000] {processor.py:186} INFO - Started process (PID=1145) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:57:52.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:57:52.672+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:57:52.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:57:52.685+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:57:52.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:57:52.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:57:52.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.040 seconds
[2024-11-27T22:58:22.957+0000] {processor.py:186} INFO - Started process (PID=1210) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:58:22.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:58:22.959+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:58:22.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:58:22.977+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:58:22.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:58:22.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:58:22.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.046 seconds
[2024-11-27T22:58:53.076+0000] {processor.py:186} INFO - Started process (PID=1275) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:58:53.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:58:53.079+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:58:53.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:58:53.093+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:58:53.090+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:58:53.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:58:53.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.039 seconds
[2024-11-27T22:59:23.294+0000] {processor.py:186} INFO - Started process (PID=1340) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:59:23.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:59:23.298+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:59:23.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:59:23.313+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:59:23.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:59:23.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:59:23.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.052 seconds
[2024-11-27T22:59:53.682+0000] {processor.py:186} INFO - Started process (PID=1406) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:59:53.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T22:59:53.685+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:59:53.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:59:53.700+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:59:53.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T22:59:53.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T22:59:53.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.042 seconds
[2024-11-27T23:00:24.229+0000] {processor.py:186} INFO - Started process (PID=1471) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:00:24.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:00:24.232+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:00:24.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:00:24.250+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:00:24.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:00:24.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:00:24.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.054 seconds
[2024-11-27T23:00:54.349+0000] {processor.py:186} INFO - Started process (PID=1536) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:00:54.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:00:54.354+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:00:54.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:00:54.370+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:00:54.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:00:54.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:00:54.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.047 seconds
[2024-11-27T23:01:24.724+0000] {processor.py:186} INFO - Started process (PID=1600) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:01:24.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:01:24.727+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:01:24.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:01:24.740+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:01:24.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:01:24.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:01:24.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.048 seconds
[2024-11-27T23:01:55.190+0000] {processor.py:186} INFO - Started process (PID=1664) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:01:55.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:01:55.193+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:01:55.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:01:55.208+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:01:55.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:01:55.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:01:55.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.039 seconds
[2024-11-27T23:02:25.347+0000] {processor.py:186} INFO - Started process (PID=1729) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:02:25.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:02:25.351+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:02:25.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:02:25.370+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:02:25.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:02:25.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:02:25.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.049 seconds
[2024-11-27T23:02:55.737+0000] {processor.py:186} INFO - Started process (PID=1794) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:02:55.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:02:55.740+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:02:55.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:02:55.753+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:02:55.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:02:55.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:02:55.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.038 seconds
[2024-11-27T23:03:26.103+0000] {processor.py:186} INFO - Started process (PID=1858) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:03:26.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:03:26.106+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:03:26.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:03:26.133+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:03:26.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:03:26.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:03:26.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.073 seconds
[2024-11-27T23:03:56.559+0000] {processor.py:186} INFO - Started process (PID=1923) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:03:56.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:03:56.562+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:03:56.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:03:56.579+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:03:56.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:03:56.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:03:56.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.054 seconds
[2024-11-27T23:04:27.087+0000] {processor.py:186} INFO - Started process (PID=1988) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:04:27.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:04:27.090+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:04:27.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:04:27.110+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:04:27.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:04:27.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:04:27.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.049 seconds
[2024-11-27T23:04:58.054+0000] {processor.py:186} INFO - Started process (PID=2053) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:04:58.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:04:58.057+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:04:58.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:04:58.071+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:04:58.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:04:58.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:04:58.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T23:05:28.468+0000] {processor.py:186} INFO - Started process (PID=2118) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:05:28.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:05:28.471+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:05:28.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:05:28.488+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:05:28.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:05:28.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:05:28.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.048 seconds
[2024-11-27T23:06:00.782+0000] {processor.py:186} INFO - Started process (PID=2174) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:06:00.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:06:00.786+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:06:00.786+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:06:00.807+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:06:00.803+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:06:00.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:06:00.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.058 seconds
[2024-11-27T23:06:32.007+0000] {processor.py:186} INFO - Started process (PID=2235) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:06:32.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:06:32.012+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:06:32.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:06:32.036+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:06:32.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:06:32.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:06:32.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.062 seconds
[2024-11-27T23:07:02.194+0000] {processor.py:186} INFO - Started process (PID=2295) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:07:02.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:07:02.196+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:07:02.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:07:02.210+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:07:02.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:07:02.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:07:02.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.038 seconds
[2024-11-27T23:07:32.932+0000] {processor.py:186} INFO - Started process (PID=2358) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:07:32.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:07:32.935+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:07:32.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:07:32.955+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:07:32.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:07:32.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:07:32.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.056 seconds
[2024-11-27T23:08:03.993+0000] {processor.py:186} INFO - Started process (PID=2424) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:08:03.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:08:03.996+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:08:03.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:08:04.010+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:08:04.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:08:04.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:08:04.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.039 seconds
[2024-11-27T23:08:34.114+0000] {processor.py:186} INFO - Started process (PID=2489) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:08:34.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:08:34.117+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:08:34.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:08:34.132+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:08:34.129+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:08:34.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:08:34.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.043 seconds
[2024-11-27T23:09:04.388+0000] {processor.py:186} INFO - Started process (PID=2554) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:09:04.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:09:04.391+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:09:04.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:09:04.406+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:09:04.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:09:04.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:09:04.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.041 seconds
[2024-11-27T23:09:35.089+0000] {processor.py:186} INFO - Started process (PID=2609) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:09:35.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:09:35.092+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:09:35.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:09:35.110+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:09:35.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:09:35.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:09:35.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.045 seconds
[2024-11-27T23:10:06.097+0000] {processor.py:186} INFO - Started process (PID=2672) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:10:06.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:10:06.101+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:10:06.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:10:06.118+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:10:06.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:10:06.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:10:06.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.045 seconds
[2024-11-27T23:10:36.250+0000] {processor.py:186} INFO - Started process (PID=2726) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:10:36.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:10:36.253+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:10:36.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:10:36.268+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:10:36.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:10:36.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:10:36.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.042 seconds
[2024-11-27T23:11:06.786+0000] {processor.py:186} INFO - Started process (PID=2791) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:11:06.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:11:06.790+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:11:06.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:11:06.808+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:11:06.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:11:06.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:11:06.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.048 seconds
[2024-11-27T23:11:37.369+0000] {processor.py:186} INFO - Started process (PID=2856) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:11:37.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:11:37.374+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:11:37.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:11:37.399+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:11:37.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:11:37.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:11:37.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.061 seconds
[2024-11-27T23:12:07.646+0000] {processor.py:186} INFO - Started process (PID=2921) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:12:07.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:12:07.650+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:12:07.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:12:07.666+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:12:07.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:12:07.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:12:07.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.042 seconds
[2024-11-27T23:12:38.296+0000] {processor.py:186} INFO - Started process (PID=2986) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:12:38.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:12:38.299+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:12:38.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:12:38.315+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:12:38.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:12:38.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:12:38.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
[2024-11-27T23:13:09.165+0000] {processor.py:186} INFO - Started process (PID=3051) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:13:09.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:13:09.170+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:13:09.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:13:09.196+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:13:09.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:13:09.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:13:09.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.065 seconds
[2024-11-27T23:13:39.617+0000] {processor.py:186} INFO - Started process (PID=3116) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:13:39.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:13:39.630+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:13:39.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:13:39.656+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:13:39.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:13:39.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:13:39.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.087 seconds
[2024-11-27T23:14:09.802+0000] {processor.py:186} INFO - Started process (PID=3181) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:14:09.803+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:14:09.806+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:14:09.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:14:09.828+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:14:09.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:14:09.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:14:09.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.055 seconds
[2024-11-27T23:14:39.924+0000] {processor.py:186} INFO - Started process (PID=3246) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:14:39.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:14:39.927+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:14:39.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:14:39.943+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:14:39.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:14:39.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:14:39.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.049 seconds
[2024-11-27T23:16:18.400+0000] {processor.py:186} INFO - Started process (PID=32) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:16:18.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:16:18.404+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:16:18.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:16:18.433+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:16:18.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:16:18.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:16:18.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.068 seconds
[2024-11-27T23:16:48.847+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:16:48.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:16:48.849+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:16:48.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:16:48.863+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:16:48.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:16:48.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:16:48.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.037 seconds
[2024-11-27T23:17:19.632+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:17:19.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:17:19.637+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:17:19.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:17:19.662+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:17:19.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:17:19.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:17:19.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.060 seconds
[2024-11-27T23:17:49.747+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:17:49.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:17:49.750+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:17:49.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:17:49.765+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:17:49.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:17:49.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:17:49.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.049 seconds
[2024-11-27T23:18:20.037+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:20.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:18:20.040+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:20.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:20.056+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:20.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:18:20.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:20.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T23:18:26.852+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:26.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:18:26.855+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:26.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:26.880+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:26.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:18:26.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:26.899+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T23:18:56.961+0000] {processor.py:186} INFO - Started process (PID=377) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:56.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:18:56.964+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:56.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:56.979+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:56.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:18:56.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:18:56.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.040 seconds
[2024-11-27T23:19:27.400+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:19:27.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:19:27.403+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:19:27.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:19:27.421+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:19:27.417+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:19:27.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:19:27.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
[2024-11-27T23:19:57.628+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:19:57.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:19:57.631+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:19:57.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:19:57.649+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:19:57.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:19:57.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:19:57.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.053 seconds
[2024-11-27T23:20:27.843+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:20:27.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:20:27.847+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:20:27.846+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:20:27.862+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:20:27.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:20:27.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:20:27.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T23:20:58.270+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:20:58.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:20:58.273+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:20:58.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:20:58.289+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:20:58.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:20:58.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:20:58.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.043 seconds
[2024-11-27T23:21:28.453+0000] {processor.py:186} INFO - Started process (PID=703) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:21:28.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:21:28.456+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:21:28.456+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:21:28.471+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:21:28.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:21:28.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:21:28.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T23:21:58.631+0000] {processor.py:186} INFO - Started process (PID=768) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:21:58.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:21:58.634+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:21:58.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:21:58.651+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:21:58.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:21:58.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:21:58.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.042 seconds
[2024-11-27T23:22:29.268+0000] {processor.py:186} INFO - Started process (PID=833) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:22:29.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:22:29.273+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:22:29.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:22:29.289+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:22:29.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:22:29.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:22:29.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.053 seconds
[2024-11-27T23:22:59.556+0000] {processor.py:186} INFO - Started process (PID=898) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:22:59.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:22:59.559+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:22:59.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:22:59.574+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:22:59.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:22:59.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:22:59.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.041 seconds
[2024-11-27T23:23:30.132+0000] {processor.py:186} INFO - Started process (PID=963) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:23:30.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:23:30.135+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:23:30.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:23:30.151+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:23:30.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:23:30.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:23:30.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.052 seconds
[2024-11-27T23:24:00.805+0000] {processor.py:186} INFO - Started process (PID=1028) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:24:00.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:24:00.808+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:24:00.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:24:00.823+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:24:00.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:24:00.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:24:00.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T23:24:30.975+0000] {processor.py:186} INFO - Started process (PID=1093) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:24:30.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:24:30.978+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:24:30.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:24:30.997+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:24:30.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:24:30.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:24:31.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.045 seconds
[2024-11-27T23:25:01.118+0000] {processor.py:186} INFO - Started process (PID=1158) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:25:01.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:25:01.121+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:25:01.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:25:01.142+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:25:01.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:25:01.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:25:01.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.057 seconds
[2024-11-27T23:25:31.432+0000] {processor.py:186} INFO - Started process (PID=1223) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:25:31.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:25:31.435+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:25:31.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:25:31.451+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:25:31.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:25:31.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:25:31.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.040 seconds
[2024-11-27T23:26:02.207+0000] {processor.py:186} INFO - Started process (PID=1288) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:26:02.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:26:02.210+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:26:02.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:26:02.226+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:26:02.222+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:26:02.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:26:02.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.041 seconds
[2024-11-27T23:26:32.418+0000] {processor.py:186} INFO - Started process (PID=1353) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:26:32.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:26:32.421+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:26:32.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:26:32.439+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:26:32.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:26:32.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:26:32.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.042 seconds
[2024-11-27T23:27:02.965+0000] {processor.py:186} INFO - Started process (PID=1418) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:27:02.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:27:02.968+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:27:02.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:27:02.983+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:27:02.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:27:02.984+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:27:03.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.040 seconds
[2024-11-27T23:27:33.594+0000] {processor.py:186} INFO - Started process (PID=1483) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:27:33.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:27:33.597+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:27:33.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:27:33.612+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:27:33.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:27:33.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:27:33.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.039 seconds
[2024-11-27T23:28:04.171+0000] {processor.py:186} INFO - Started process (PID=1548) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:28:04.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:28:04.174+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:28:04.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:28:04.189+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:28:04.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:28:04.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:28:04.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.038 seconds
[2024-11-27T23:28:34.376+0000] {processor.py:186} INFO - Started process (PID=1613) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:28:34.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:28:34.378+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:28:34.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:28:34.393+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:28:34.391+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:28:34.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:28:34.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.039 seconds
[2024-11-27T23:29:04.827+0000] {processor.py:186} INFO - Started process (PID=1678) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:29:04.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:29:04.830+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:29:04.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:29:04.849+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:29:04.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:29:04.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:29:04.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.056 seconds
[2024-11-27T23:29:35.338+0000] {processor.py:186} INFO - Started process (PID=1742) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:29:35.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:29:35.342+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:29:35.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:29:35.356+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:29:35.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:29:35.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:29:35.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.041 seconds
[2024-11-27T23:30:05.545+0000] {processor.py:186} INFO - Started process (PID=1807) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:30:05.546+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:30:05.548+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:30:05.548+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:30:05.566+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:30:05.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:30:05.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:30:05.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.052 seconds
[2024-11-27T23:30:36.532+0000] {processor.py:186} INFO - Started process (PID=1872) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:30:36.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:30:36.535+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:30:36.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:30:36.554+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:30:36.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:30:36.556+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:30:36.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T23:31:06.816+0000] {processor.py:186} INFO - Started process (PID=1937) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:31:06.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:31:06.823+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:31:06.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:31:06.840+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:31:06.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:31:06.842+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:31:06.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.048 seconds
[2024-11-27T23:31:36.939+0000] {processor.py:186} INFO - Started process (PID=2002) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:31:36.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:31:36.942+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:31:36.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:31:36.956+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:31:36.953+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:31:36.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:31:36.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.040 seconds
[2024-11-27T23:32:07.176+0000] {processor.py:186} INFO - Started process (PID=2067) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:32:07.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:32:07.179+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:32:07.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:32:07.200+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:32:07.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:32:07.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:32:07.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.046 seconds
[2024-11-27T23:32:38.001+0000] {processor.py:186} INFO - Started process (PID=2132) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:32:38.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:32:38.005+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:32:38.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:32:38.021+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:32:38.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:32:38.022+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:32:38.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T23:33:08.448+0000] {processor.py:186} INFO - Started process (PID=2197) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:33:08.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:33:08.452+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:33:08.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:33:08.469+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:33:08.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:33:08.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:33:08.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.053 seconds
[2024-11-27T23:33:39.422+0000] {processor.py:186} INFO - Started process (PID=2262) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:33:39.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:33:39.426+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:33:39.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:33:39.443+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:33:39.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:33:39.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:33:39.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.045 seconds
[2024-11-27T23:34:09.667+0000] {processor.py:186} INFO - Started process (PID=2327) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:34:09.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:34:09.670+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:34:09.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:34:09.686+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:34:09.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:34:09.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:34:09.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T23:34:39.814+0000] {processor.py:186} INFO - Started process (PID=2392) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:34:39.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:34:39.817+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:34:39.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:34:39.832+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:34:39.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:34:39.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:34:39.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.051 seconds
[2024-11-27T23:35:10.421+0000] {processor.py:186} INFO - Started process (PID=2457) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:35:10.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:35:10.424+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:35:10.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:35:10.439+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:35:10.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:35:10.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:35:10.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.040 seconds
[2024-11-27T23:35:41.391+0000] {processor.py:186} INFO - Started process (PID=2521) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:35:41.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:35:41.394+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:35:41.394+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:35:41.410+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:35:41.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:35:41.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:35:41.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.042 seconds
[2024-11-27T23:36:12.565+0000] {processor.py:186} INFO - Started process (PID=2575) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:36:12.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:36:12.569+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:36:12.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:36:12.593+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:36:12.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:36:12.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:36:12.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.071 seconds
[2024-11-27T23:36:42.965+0000] {processor.py:186} INFO - Started process (PID=2632) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:36:42.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:36:42.968+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:36:42.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:36:42.985+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:36:42.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:36:42.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:36:43.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.052 seconds
[2024-11-27T23:37:13.470+0000] {processor.py:186} INFO - Started process (PID=2697) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:37:13.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:37:13.474+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:37:13.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:37:13.491+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:37:13.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:37:13.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:37:13.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.046 seconds
[2024-11-27T23:37:44.074+0000] {processor.py:186} INFO - Started process (PID=2748) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:37:44.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:37:44.077+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:37:44.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:37:44.095+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:37:44.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:37:44.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:37:44.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.048 seconds
[2024-11-27T23:38:14.478+0000] {processor.py:186} INFO - Started process (PID=2809) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:38:14.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:38:14.481+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:38:14.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:38:14.496+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:38:14.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:38:14.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:38:14.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.041 seconds
[2024-11-27T23:38:44.847+0000] {processor.py:186} INFO - Started process (PID=2867) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:38:44.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:38:44.849+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:38:44.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:38:44.865+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:38:44.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:38:44.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:38:44.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.049 seconds
[2024-11-27T23:39:15.232+0000] {processor.py:186} INFO - Started process (PID=2932) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:39:15.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:39:15.235+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:39:15.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:39:15.248+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:39:15.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:39:15.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:39:15.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.047 seconds
[2024-11-27T23:39:45.729+0000] {processor.py:186} INFO - Started process (PID=2997) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:39:45.730+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:39:45.732+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:39:45.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:39:45.750+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:39:45.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:39:45.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:39:45.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
[2024-11-27T23:40:15.879+0000] {processor.py:186} INFO - Started process (PID=3062) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:40:15.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:40:15.882+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:40:15.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:40:15.899+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:40:15.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:40:15.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:40:15.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
[2024-11-27T23:40:46.340+0000] {processor.py:186} INFO - Started process (PID=3127) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:40:46.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:40:46.343+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:40:46.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:40:46.359+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:40:46.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:40:46.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:40:46.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T23:41:16.914+0000] {processor.py:186} INFO - Started process (PID=3192) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:41:16.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:41:16.917+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:41:16.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:41:16.930+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:41:16.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:41:16.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:41:16.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.048 seconds
[2024-11-27T23:42:49.308+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:42:49.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:42:49.312+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:42:49.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:42:49.332+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:42:49.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:42:49.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:42:49.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.061 seconds
[2024-11-27T23:43:19.755+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:43:19.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:43:19.759+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:43:19.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:43:19.777+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:43:19.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:43:19.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:43:19.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.057 seconds
[2024-11-27T23:43:50.836+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:43:50.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:43:50.839+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:43:50.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:43:50.855+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:43:50.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:43:50.856+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:43:50.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.042 seconds
[2024-11-27T23:44:21.414+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:44:21.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:44:21.418+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:44:21.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:44:21.434+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:44:21.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:44:21.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:44:21.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.053 seconds
[2024-11-27T23:44:51.762+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:44:51.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:44:51.765+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:44:51.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:44:51.781+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:44:51.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:44:51.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:44:51.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.042 seconds
[2024-11-27T23:45:21.932+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:45:21.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:45:21.934+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:45:21.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:45:21.949+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:45:21.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:45:21.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:45:21.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.050 seconds
[2024-11-27T23:45:52.313+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:45:52.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:45:52.315+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:45:52.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:45:52.328+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:45:52.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:45:52.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:45:52.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.049 seconds
[2024-11-27T23:46:22.789+0000] {processor.py:186} INFO - Started process (PID=490) to work on /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:46:22.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2024-11-27T23:46:22.792+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:46:22.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:46:22.808+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:46:22.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-11-27T23:46:22.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2024-11-27T23:46:22.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.044 seconds
